### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by romain1206** [el-bakkali/esp32-a1s-sendspin#1]
hello

i have a error of compilation

many thanks

INFO ESPHome 2026.1.4
INFO Reading configuration /config/esphome/esphome-web-25a2f0.yaml...
INFO Updating https://github.com/esphome/esphome.git@pull/12253/head
INFO Updating https://github.com/esphome/esphome.git@pull/12254/head
INFO Updating https://github.com/esphome/esphome.git@pull/12258/head
INFO Updating https://github.com/esphome/esphome.git@pull/12284/head
INFO Updating https://github.com/esphome/esphome.git@pull/12429/head
WARNING GPIO0 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq/#why-am-i-getting-a-warning-about-strapping-pins
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq/#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Applying optimized lwip settings: 65KB TCP windows, 64 mailbox sizes
INFO Applying optimized WiFi settings: 64 RX buffers, 64 TX buffers
INFO Setting CONFIG_LWIP_MAX_SOCKETS to 15 (registered: api=4, captive_portal=4, mdns=2, ota=1, sendspin_websocket_client=1, sendspin_websocket_server=3)
INFO Compiling app... Build path: /data/build/esp32-a1s
Processing esp32-a1s (board: esp-wrover-kit; framework: espidf; platform: https://github.com/pioarduino/platform-espressif32/releases/download/55.03.35/platform-espressif32.zip)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - contrib-piohome @ 3.4.4 
 - framework-espidf @ 3.50502.0 (5.5.2) 
 - tool-cmake @ 4.0.3 
 - tool-esp-rom-elfs @ 2024.10.11 
 - tool-esptoolpy @ 5.1.0 
 - tool-mklittlefs @ 3.2.0 
 - tool-ninja @ 1.13.1 
 - tool-scons @ 4.40801.0 (4.8.1) 
 - toolchain-xtensa-esp-elf @ 14.2.0+20251107
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.10
|-- ArduinoJson @ 7.4.2
Compiling .pioenvs/esp32-a1s/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/esp32-a1s/src/esphome/components/ota/ota_backend_host.cpp.o
Compiling .pioenvs/esp32-a1s/src/esphome/components/output/automation.cpp.o
Compiling .pioenvs/esp32-a1s/src/esphome/components/output/float_output.cpp.o
Compiling .pioenvs/esp32-a1s/src/esphome/components/psram/psram.cpp.o
Compiling .pioenvs/esp32-a1s/src/esphome/components/resampler/speaker/resampler_speaker.cpp.o
Compiling .pioenvs/esp32-a1s/src/esphome/components/safe_mode/safe_mode.cpp.o
Compiling .pioenvs/esp32-a1s/src/esphome/components/select/select.cpp.o
src/esphome/components/mdns/mdns_esp32.cpp: In function 'void esphome::mdns::register_esp32(MDNSComponent*, esphome::StaticVector<MDNSService, 2>&)':
src/esphome/components/mdns/mdns_esp32.cpp:32:52: error: wrong number of template arguments (2, should be 1)
   32 |     SmallBufferWithHeapFallback<16, mdns_txt_item_t> txt_records(service.txt_records.size());
      |                                                    ^
In file included from src/esphome/core/component.h:8,
                 from src/esphome/core/application.h:10,
                 from src/esphome/components/mdns/mdns_esp32.cpp:5:
src/esphome/core/helpers.h:368:35: note: provided for 'template<unsigned int STACK_SIZE> class esphome::SmallBufferWithHeapFallback'
  368 | template<size_t STACK_SIZE> class SmallBufferWithHeapFallback {
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/mdns/mdns_esp32.cpp:37:19: error: request for member 'get' in 'txt_records', which is of non-class type 'int'
   37 |       txt_records.get()[i].key = MDNS_STR_ARG(record.key);
      |                   ^~~
src/esphome/components/mdns/mdns_esp32.cpp:38:19: error: request for member 'get' in 'txt_records', which is of non-class type 'int'
   38 |       txt_records.get()[i].value = MDNS_STR_ARG(record.value);
      |                   ^~~
src/esphome/components/mdns/mdns_esp32.cpp:42:40: error: request for member 'get' in 'txt_records', which is of non-class type 'int'
   42 |                            txt_records.get(), service.txt_records.size());
      |                                        ^~~
*** [.pioenvs/esp32-a1s/src/esphome/components/mdns/mdns_esp32.cpp.o] Error 1
========================= [FAILED] Took 10.88 seconds =========================

**Comment by WhyDoYouMakeUsDoThis** [comment]
Confirmed.  I have the same error.  Other devices compile correctly

**Comment by WhyDoYouMakeUsDoThis** [comment]
The error comes from the upstream PR 12284, as that fails if I try to include it as a custom component on a test device compile.

Noted here in the PR comments 
https://github.com/esphome/esphome/pull/12284#issuecomment-3873448455

**Comment by WhyDoYouMakeUsDoThis** [comment]
PR 12284 has been moved to the Dev branch on ESPhome.  It was split to two PRs, one is currently passing the MDNS one is not yet.  
The MDNS one can be followed here: https://github.com/esphome/esphome/pull/14013

**Comment by WhyDoYouMakeUsDoThis** [comment]
The PRs now compile with 2026.2.0.  There's a new list of component locations to pull from as a result of the breaking changes from PR#12284.  Documentation for the needed changes are in that PR

**Comment by romain1206** [comment]
it's work with

`# ESP32-A1S Audio Kit - Sendspin Configuration
# Working config for ESPHome 2026.1.x with Music Assistant Sendspin support
# Board: AI-Thinker ESP32-A1S Audio Kit (ES8388 codec)
#
# GitHub: https://github.com/el-bakkali/esp32-a1s-sendspin
# 
# Requirements:
#   - ESPHome 2026.1.x or later
#   - Music Assistant 2.7.0 beta 19 or later
#
# Setup:
#   1. Copy secrets.yaml.example to secrets.yaml
#   2. Fill in your WiFi and API credentials
#   3. Flash with: esphome run esp32-a1s.yaml

esphome:
  name: esp32-a1s
  friendly_name: ESP32-A1S
  on_boot:
    priority: -100
    then:
      - select.set:
          id: dac_output_select
          option: "BOTH"

esp32:
  board: esp-wrover-kit
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXX"

ota:
  - platform: esphome
    password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_mdp

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-A1S Fallback Hotspot"
    password: "ivzoJF8E7zem"
captive_portal:

psram:

# ===== ES8388 Audio Codec Configuration =====
# Reference: https://esphome.io/components/audio_dac/es8388/

i2c:
  sda: GPIO33
  scl: GPIO32
  frequency: 100kHz
  id: bus_a

audio_dac:
  - platform: es8388
    id: es8388_dac

select:
  - platform: es8388
    es8388_id: es8388_dac
    dac_output:
      id: dac_output_select
      name: "DAC Output"
    adc_input_mic:
      name: "ADC Input MIC"

i2s_audio:
  id: i2s_output
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO27
  i2s_mclk_pin: GPIO0

# ===== Amplifier Control =====
switch:
  - platform: gpio
    pin: GPIO21
    id: mute_switch
    name: "AMP Switch"
    restore_mode: ALWAYS_ON

# ===== Microphone =====
microphone:
  - platform: i2s_audio
    i2s_din_pin: GPIO35
    id: mic1
    adc_type: external
    pdm: false
    sample_rate: 16000
    bits_per_sample: 16bit

# ===== Hardware Buttons & Sensors =====
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
      mode:
        input: true
    name: "Jack Status"

  - platform: gpio
    pin:
      number: GPIO036
      inverted: true
    name: "Key 1"
    filters:
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: GPIO013
      inverted: true
    name: "Key 2"
    filters:
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: GPIO019
      inverted: true
    name: "Key 3"
    filters:
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: GPIO023
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Key 4"
    filters:
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: GPIO018
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Key 5"
    filters:
      - delayed_off: 10ms

  - platform: gpio
    pin:
      number: GPIO005
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Key 6"
    filters:
      - delayed_off: 10ms

# ===== Status LED =====
output:
  - platform: ledc
    pin:
      number: GPIO22
      inverted: true
    id: output_led

light:
  - platform: binary
    name: "Red LED"
    id: red_led
    output: output_led
    restore_mode: ALWAYS_OFF

# ===== Sendspin External Components =====
# Using specific commits/PRs for ESPHome 2026.1.x compatibility
# These may be simplified once ESPHome 2026.2.0 is released
external_components:
  - source:
      type: git
      url: https://github.com/esphome/esphome
      ref: d2026b4cd74bbeb9b86941bf1887f3d93d639387
    components: [audio]
  - source: github://pr#12253
    components: [mixer]
    refresh: 0s
  - source: github://pr#12254
    components: [resampler]
    refresh: 0s
  - source:
      # Dev commit hash for squash merge from PR#12258
      type: git
      url: https://github.com/esphome/esphome
      ref: 264c8faedd0ab956b0437ec2ecc0bacae1708923
    components: [media_player]
  - source:
      # Dev commit hash for squash merge from PR#14013
      type: git
      url: https://github.com/esphome/esphome
      ref: ba7134ee3f870ce00d2990d84b142b734028330f
    components: [mdns]
  - source:
      # https://github.com/esphome/esphome/pull/12284
      type: git
      url: https://github.com/esphome/esphome
      ref: 119a5c25a483c58b3d58a35c8cec95495c6491c2
    components: [sendspin]
  - source: github://pr#12429
    components: [media_source, speaker_source]
    refresh: 0s

# ===== Speaker & Audio Pipeline =====
speaker:
  - platform: i2s_audio
    i2s_audio_id: i2s_output
    sample_rate: 48000
    id: i2s_speaker_id
    i2s_dout_pin: GPIO26
    bits_per_sample: 32bit
    dac_type: external
    channel: stereo
    timeout: never
    buffer_duration: 100ms
    audio_dac: es8388_dac

  - platform: mixer
    id: mixer_speaker_id
    output_speaker: i2s_speaker_id
    num_channels: 2
    source_speakers:
      - id: announcement_mixer_input
        timeout: never
      - id: media_mixer_input
        timeout: never

  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixer_input
    sample_rate: 48000
    bits_per_sample: 16

  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixer_input
    sample_rate: 48000
    bits_per_sample: 16

# ===== Sendspin Media Player =====
sendspin:
  id: sendspin_hub

media_source:
  - platform: sendspin
    id: sendspin_source

media_player:
  - platform: speaker_source
    name: Sendspin Media Player
    id: sendspin_media_player
    volume_min: 0.4
    volume_max: 0.85
    announcement_speaker: announcement_resampling_speaker
    media_speaker: media_resampling_speaker
    sources:
      - sendspin_source

# ===== Track Metadata (Optional) =====
text_sensor:
  - platform: sendspin
    type: title
    name: Track Title

  - platform: sendspin
    type: artist
    name: Artist

  - platform: sendspin
    type: album
    name: Album

  - platform: sendspin
    type: year
    name: Year

  - platform: sendspin
    type: track
    name: Track Number`

**Comment by el-bakkali** [comment]
Hi @romain1206, apologies for the late reply — I've been quite busy lately.

This issue is now resolved. The configuration in the repo has been updated to target ESPHome 2026.2.x with the correct external component references, including the mDNS fix from PR #14013 and pinned commit hashes for all dependencies (audio, media_player, sendspin, etc.).

If you're on ESPHome 2026.2.4, the current config in the repo should compile and work without issues. Make sure to clear your `.esphome/external_components/` cache folder before recompiling to avoid stale component conflicts.

Big thanks to @WhyDoYouMakeUsDoThis for tracking down the root cause and following the upstream PRs — really appreciate the help debugging this.

Closing this as resolved.
